project:
  type: website
  output-dir: docs

website:
  title: "Thinh's DPhil"
  sidebar:
    style: "docked"
    contents:
      - 00_est_imm_profile.qmd
      - 01_chapter1.qmd
      - 03_chapter3.qmd
      - sero-vax.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true