project:
  type: website
  output-dir: docs
  render:
    - 01_res1.qmd
    - 02_res2.qmd
    - 03_res3.qmd

website:
  title: "Thinh's DPhil"
  sidebar:
    style: "docked"
    contents:
      - 01_res1.qmd
      - 02_res2.qmd
      - 03_res3.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true